/* eslint-disable no-unused-vars */
const config = {
    transition: 'slide',
    transitionSpeed: 'default',
    backgroundTransition: 'slide',
    controls: true,
    controlsLayout: 'bottom-right',
    controlsBackArrows: 'faded',
    progress: true,
    hashOneBasedIndex: true,
    jumpToSlide: true,
    keyboard: true,
    overview: true,
    touch: true,
    loop: false,
    shuffle: false,
    fragments: true,
    fragmentInURL: true,
    embedded: false,
    help: true,
    pause: true,
    showNotes: false,
    autoPlayMedia: null,
    autoSlide: 0,
    autoSlideStoppable: true,
    pdfMaxPagesPerSlide: 'default',
    pdfSeparateFragments: true,
    pdfPageHeightOffset: -1,
    viewDistance: 3,
    display: 'block',
    hideInactiveCursor: true,
    hideCursorTime: 5000,
}
/* eslint-enable no-unused-vars */
